networks:
  tp1:

services:
  tp1:
    build: .
    environment:
      - DB_SERVER=db
    depends_on:
      - db
    networks:
      - tp1
    ports:
      - 127.0.0.1:80:80

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=tp1
      - MYSQL_DATABASE=tp1
      - MYSQL_USER=tp1
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tp1
